name: First workflow

on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello First Github Actions"

      - name: Node version
        run: node -v
      
      - name: current directory
        run: pwd